### PR TITLE
Updates to latest go and wasmer

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Since I was here, I figured I'd bump the libraries. Nice that the example works!

```bash
## Build it
$ (cd example; go build .)

## Ensure the linked libraries are there
$ otool -L example/example
example/example:
	@rpath/libwasmer.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60158.100.133)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)

$ du -k example/example 
10512	example/example

$ du -k vendor/github.com/wasmerio/wasmer-go/wasmer/packaged/lib/darwin-amd64/libwasmer.dylib 
10404	vendor/github.com/wasmerio/wasmer-go/wasmer/packaged/lib/darwin-amd64/libwasmer.dylib

## try it
$ (cd example; ./example)
receive request /
print header from server host, User-Agent -> [curl/7.79.1]
print header from server host, Accept -> [*/*]
[http_wasm_example.cc:33]::onRequestHeaders() print from wasm, onRequestHeaders, context id: 2
[http_wasm_example.cc:38]::onRequestHeaders() print from wasm, Accept -> */*
[http_wasm_example.cc:38]::onRequestHeaders() print from wasm, User-Agent -> curl/7.79.1
```

PS if the intention is to keep floor go 1.14, definitely wazero won't work as we follow Go's support policy, and even if we didn't 1.14 is too far back.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
ps I tried to submit the CLA twice it just returned to the same page each time. If this didn't accept, feel free to close the PR as all I did was..

```bash
go get -u github.com/wasmerio/wasmer-go
go get -u github.com/stretchr/testify
go mod tidy
go vendor
```

**Comment by antJack** [comment]
Welcome PR. Plz retry signing CLA again? maybe there is some error happened. If successed, it should be:

image

**Comment by codefromthecrypt** [comment]
A lot of timeouts, but 🤞 this one worked!

Screen Shot 2022-04-21 at 6 21 03 PM

**Comment by codefromthecrypt** [comment]
I can see the bot isn't responding. It took almost a minute for the page to load, even if I VPN didn't make any difference. I think there's a problem with it, especially that even when it responded and accepted my CLA it still doesn't know it did.

**Comment by antJack** [comment]
Sorry for bad experience of the CLA. Try re-open this PR to enforce the CLA check again?

**Comment by codefromthecrypt** [comment]
good idea. it worked!

**Comment by antJack** [comment]
Well done

**Pull request merged**
